name: image_classification
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy<2.0
  - scikit-learn
  - matplotlib
  - seaborn
  - pillow
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets
  - jupyter_contrib_nbextensions
  - scipy
  - tqdm
  - pip:
      - tensorflow==2.14.0
      - opencv-python
      - requests
      - plotly
      - optuna
      - streamlit
